{{- if .Values.database.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "corgi.fullname" . }}-db
  labels:
    {{- include "corgi.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.database.instances }}
  imageName: {{ .Values.database.image }}

  bootstrap:
    initdb:
      database: {{ .Values.database.database }}
      owner: {{ .Values.database.owner }}

  storage:
    storageClass: {{ .Values.database.storage.storageClass }}
    size: {{ .Values.database.storage.size }}
{{- end }}
