apiVersion: v1
kind: Secret
metadata:
  name: {{ include "corgi-backend.fullname" . }}-db-superuser-bootstrap
  labels:
    {{- include "corgi-backend.labels" . | nindent 4 }}
type: Opaque
# data: keys must be base64-encoded
stringData:
  username: admin
  password: password1234
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "corgi-backend.fullname" . }}-db-bootstrap
  labels:
    {{- include "corgi-backend.labels" . | nindent 4 }}
type: Opaque
# data: keys must be base64-encoded
stringData:
  username: admin
  password: password1234
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "corgi-backend.fullname" . }}-github-pat
  labels:
    {{- include "corgi-backend.labels" . | nindent 4 }}
type: Opaque
# data: keys must be base64-encoded
stringData:
  token: someGHtoken
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "corgi-backend.fullname" . }}-db-app
type: Opaque
stringData:
  uri: "postgresql://admin:password1234@{{ include "corgi-backend.fullname" . }}-db-rw:5432/corgi"
